### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type' using copier 

### ISSUE THREAD

**Issue by ggiesen** [salt-extensions/salt-extension-copier#112]
I receive the following error when attempting to run copier 9.4.1 on AlmaLinux 9/Python 3.9:

```
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

```
$ copier copy --trust https://github.com/salt-extensions/salt-extension-copier salt-ext-foo

Welcome to salt-extension-copier!

Even after generation, this template can be used to perform
updates to your project's boilerplate.


Anything unclear? Visit the comprehensive user documentation:

  ▶ https://salt-extensions.github.io/salt-extension-copier/

🎤 Name of the project and generated extensions (don't include `saltext-` prefix)
   foo
🎤 Author for project metadata
   John Doe
🎤 The author's contact email address
   user@example.com
🎤 The full name of the integrated service. If this extension does not integrate one, just leave this empty.
   Foo
🎤 A summary for project metadata and the readme
   Salt Extension for interacting with Foo
🎤 The project's homepage (usually the URL of the hosted repo)
   https://github.com/salt-extensions/saltext-foo
🎤 The project's repo URL
   https://github.com/salt-extensions/saltext-foo
🎤 The project's issue tracker URL
   https://github.com/salt-extensions/saltext-foo/issues
🎤 The name of the Python package (without `saltext.` prefix)
   foo
🎤 Choose a license for the project
   apache
🎤 Which module types should be implemented
   done (2 selections)
🎤 Minimum Salt version to support
   3006
🎤 Minimum Python version to support
   3.9
🎤 The maximum Salt major version to support
   3007
🎤 Omit the `saltext` namespace
   No
🎤 Generate pytest fixtures for salt-ssh
   No
🎤 Add support for test containers in functional/integration tests
   No
🎤 Supported OS. Influences where tests run.
   [Linux]
🎤 When to automatically deploy CI built docs to GitHub Pages. Does not support versioned docs currently. Requires Settings > Pages > Build and deployment source to be `GitHub Actions`.
   never
🎤 The project's documentation URL (optional)
 
🎤 Optionally provide a contact for Code of Conduct violation reports.
 
🎤 Copyright range beginning year
   2024
🎤 Suppress some Pylint messages that can cause noise or be difficult to solve with legacy code.
   No

Copying from template version 0.6.0
    create  README.md 
    create  noxfile.py
    create  src
    create  src/saltext/foo
    create  src/saltext/foo/modules
    create  src/saltext/foo/modules/foo_mod.py
    create  src/saltext/foo/modules/__init__.py
    create  src/saltext/foo/__init__.py
    create  src/saltext/foo/states
    create  src/saltext/foo/states/foo_mod.py
    create  src/saltext/foo/states/__init__.py
    create  CONTRIBUTING.md
    create  .pre-commit-config.yaml
    create  CHANGELOG.md
    create  LICENSE
    create  .envrc
    create  pyproject.toml
    create  NOTICE
    create  changelog
    create  changelog/.template.jinja
    create  docs
    create  docs/ref
    create  docs/ref/.gitkeep
    create  docs/topics
    create  docs/topics/installation.md
    create  docs/_static
    create  docs/_static/.gitkeep
    create  docs/make.bat
    create  docs/index.rst
    create  docs/Makefile
    create  docs/_ext
    create  docs/_ext/saltdomain.py
    create  docs/sitevars.rst
    create  docs/changelog.md
    create  docs/conf.py
    create  CODE-OF-CONDUCT.md
    create  .copier-answers.yml
    create  setup.py
    create  tests
    create  tests/unit
    create  tests/unit/modules
    create  tests/unit/modules/test_foo.py
    create  tests/unit/modules/__init__.py
    create  tests/unit/conftest.py
    create  tests/unit/__init__.py
    create  tests/unit/states
    create  tests/unit/states/test_foo.py
    create  tests/unit/states/__init__.py
    create  tests/__init__.py
    create  tests/conftest.py
    create  tests/integration
    create  tests/integration/modules
    create  tests/integration/modules/test_foo.py
    create  tests/integration/modules/__init__.py
    create  tests/integration/__init__.py
    create  tests/integration/conftest.py
    create  tests/integration/states
    create  tests/integration/states/__init__.py
    create  tests/functional
    create  tests/functional/modules
    create  tests/functional/modules/test_foo.py
    create  tests/functional/modules/__init__.py
    create  tests/functional/conftest.py
    create  tests/functional/__init__.py
    create  tests/functional/states
    create  tests/functional/states/test_foo.py
    create  tests/functional/states/__init__.py
    create  .pylintrc
    create  .github
    create  .github/ISSUE_TEMPLATE
    create  .github/ISSUE_TEMPLATE/bug_report.md
    create  .github/ISSUE_TEMPLATE/docs.md
    create  .github/ISSUE_TEMPLATE/config.yml
    create  .github/ISSUE_TEMPLATE/feature_request.md
    create  .github/ISSUE_TEMPLATE/tech-debt.md
    create  .github/PULL_REQUEST_TEMPLATE.md
    create  .github/workflows
    create  .github/workflows/prepare-release-action.yml
    create  .github/workflows/package-action.yml
    create  .github/workflows/docs-action.yml
    create  .github/workflows/test-action.yml
    create  .github/workflows/tag.yml
    create  .github/workflows/pr.yml
    create  .github/workflows/ci.yml
    create  .github/workflows/deploy-docs-action.yml
    create  .github/workflows/deploy-package-action.yml
    create  .github/workflows/pre-commit-action.yml
    create  .github/workflows/get-changed-files.yml
    create  .github/ISSUE_TEMPLATE.md
    create  tools
    create  tools/initialize.py
    create  tools/helpers
    create  tools/helpers/pre_commit.py
    create  tools/helpers/git.py
    create  tools/helpers/cmd.py
    create  tools/helpers/__init__.py
    create  tools/helpers/copier.py
    create  tools/helpers/prompt.py
    create  tools/helpers/venv.py
    create  tools/version.py
    create  .gitignore
    create  .coveragerc
    create  .codecov.yml
    create  .pre-commit-hooks
    create  .pre-commit-hooks/check-cli-examples.py
    create  .pre-commit-hooks/make-autodocs.py

 > Running task 1 of 1: "/home/user/.local/share/pipx/venvs/copier/bin/python" "/tmp/copier.vcs.clone.rj5uxxvw/tasks/initialize.py" init
Traceback (most recent call last):
  File "/tmp/copier.vcs.clone.rj5uxxvw/tasks/initialize.py", line 11, in <module>
    from helpers.git import ensure_git
  File "/tmp/copier.vcs.clone.rj5uxxvw/project/tools/helpers/git.py", line 3, in <module>
    from .cmd import git
  File "/tmp/copier.vcs.clone.rj5uxxvw/project/tools/helpers/cmd.py", line 24, in <module>
    class ProcessResult:
  File "/tmp/copier.vcs.clone.rj5uxxvw/project/tools/helpers/cmd.py", line 31, in ProcessResult
    stdout: str | bytes
TypeError: unsupported operand type(s) for |: 'type' and 'type'
Traceback (most recent call last):
  File "/home/user/.local/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
  File "/home/user/.local/share/pipx/venvs/copier/lib64/python3.9/site-packages/plumbum/cli/application.py", line 640, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/home/user/.local/share/pipx/venvs/copier/lib64/python3.9/site-packages/plumbum/cli/application.py", line 635, in run
    retcode = inst.main(*tailargs)
  File "/home/user/.local/share/pipx/venvs/copier/lib64/python3.9/site-packages/copier/cli.py", line 281, in main
    return _handle_exceptions(inner)
  File "/home/user/.local/share/pipx/venvs/copier/lib64/python3.9/site-packages/copier/cli.py", line 70, in _handle_exceptions
    method()
  File "/home/user/.local/share/pipx/venvs/copier/lib64/python3.9/site-packages/copier/cli.py", line 279, in inner
    worker.run_copy()
  File "/home/user/.local/share/pipx/venvs/copier/lib64/python3.9/site-packages/copier/main.py", line 237, in __exit__
    raise value
  File "/home/user/.local/share/pipx/venvs/copier/lib64/python3.9/site-packages/copier/cli.py", line 279, in inner
    worker.run_copy()
  File "/home/user/.local/share/pipx/venvs/copier/lib64/python3.9/site-packages/copier/main.py", line 847, in run_copy
    self._execute_tasks(self.template.tasks)
  File "/home/user/.local/share/pipx/venvs/copier/lib64/python3.9/site-packages/copier/main.py", line 332, in _execute_tasks
    subprocess.run(task_cmd, shell=use_shell, check=True, env=local.env)
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '"/home/user/.local/share/pipx/venvs/copier/bin/python" "/tmp/copier.vcs.clone.rj5uxxvw/tasks/initialize.py" init' returned non-zero exit status 1.
```

**Comment by ggiesen** [comment]
Looks like this maybe this was broken in https://github.com/salt-extensions/salt-extension-copier/pull/50 ? The union `|` operator is only available in Python 3.10, added as part of [PEP-604](https://peps.python.org/pep-0604/).  What is the minimum version of Python this project targets? It seems to at least allow targeting Python 3.9 for the extension itself.

**Comment by ggiesen** [comment]
I managed to work around this by install copier using python3.11:

```
$ pipx uninstall copier
uninstalled copier! ✨ 🌟 ✨
$ python3.11 -m pip install --user pipx
Collecting pipx
  Downloading pipx-1.7.1-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 973.8 kB/s eta 0:00:00
Collecting argcomplete>=1.9.4
  Downloading argcomplete-3.5.1-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 1.8 MB/s eta 0:00:00
Collecting packaging>=20
  Using cached packaging-24.2-py3-none-any.whl (65 kB)
Collecting platformdirs>=2.1
  Using cached platformdirs-4.3.6-py3-none-any.whl (18 kB)
Collecting userpath!=1.9,>=1.6
  Using cached userpath-1.9.2-py3-none-any.whl (9.1 kB)
Collecting click
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Installing collected packages: platformdirs, packaging, click, argcomplete, userpath, pipx
Successfully installed argcomplete-3.5.1 click-8.1.7 packaging-24.2 pipx-1.7.1 platformdirs-4.3.6 userpath-1.9.2
$ python3.11 -m pipx install copier
  installed package copier 9.4.1, installed using Python 3.11.9
  These apps are now globally available
    - copier
$ python3.11 -m pipx inject copier copier-templates-extensions
  injected package copier-templates-extensions into venv copier
done! ✨ 🌟 ✨
[ggiesen@GTAG00001:~]$ copier copy --trust https://github.com/salt-extensions/salt-extension-copier salt-ext-foo

**Comment by lkubb** [comment]
Thanks for your report!

Yes, while generated projects are supposed to be compatible with 3.9, sometimes the dev env gets out of sync (some dev tools tend to drop old Python versions more aggressively). The best bet is 3.10 since it's what the Salt onedir and the CI tests of this template are using.

This specific case of breakage can be fixed easily though, I'll release a fix soon. 👍
